# Generated by Django 5.2.3 on 2026-02-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cvd_risk_model_inputfeatures",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="cvd_risk_model_inputfeatures",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="cvd_risk_model_inputfeatures",
            name="encoded_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.cvd_risk_questionresponseoptions",
            ),
        ),
        migrations.AlterField(
            model_name="cvd_risk_model_inputfeatures",
            name="feature_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cvd_risk_model_inputfeatures",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.cvd_risk_questionnaire",
            ),
        ),
        migrations.AlterModelTable(
            name="cvd_risk_model_inputfeatures",
            table=None,
        ),
    ]
