# Generated by Django 5.2.3 on 2026-06-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_cvd_risk_model_inputfeatures_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicianPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_access_cvd", models.BooleanField(default=True)),
                ("can_access_tavi", models.BooleanField(default=True)),
                (
                    "clinician",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="accounts.clinicians",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clinician Permissions",
                "db_table": "Clinician_Permissions",
            },
        ),
    ]
