# Generated by Django 5.2.3 on 2026-07-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_clinicianfeedback_patientfeedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientfeedback",
            name="rating",
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="additional_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="confusing_or_difficult",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="instruction_clarity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very unclear"),
                    (2, "2 = Unclear"),
                    (3, "3 = Neutral"),
                    (4, "4 = Clear"),
                    (5, "5 = Very clear"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="learned_about_other",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="learned_about_platform",
            field=models.CharField(
                choices=[
                    ("gp", "From my GP / doctor"),
                    ("cardiologist", "From a specialist (cardiologist)"),
                    ("research", "From a research study invitation"),
                    ("family_friend", "From a family member or friend"),
                    ("social_media", "From social media or online search"),
                    ("other", "Other"),
                ],
                default=3,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="liked_most",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="overall_satisfaction",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very dissatisfied"),
                    (2, "2 = Dissatisfied"),
                    (3, "3 = Neutral"),
                    (4, "4 = Satisfied"),
                    (5, "5 = Very satisfied"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="plans_to_discuss_results",
            field=models.CharField(
                choices=[("no", "No"), ("yes", "Yes"), ("unsure", "Not sure")],
                default=3,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="platform_usage_count",
            field=models.CharField(
                choices=[
                    ("first_time", "This is my first time"),
                    ("2_to_5", "2–5 times"),
                    ("more_than_5", "More than 5 times"),
                ],
                default=3,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="prediction_confidence",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Not confident"),
                    (2, "2 = Slightly confident"),
                    (3, "3 = Neutral"),
                    (4, "4 = Confident"),
                    (5, "5 = Very confident"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="questionnaire_completion_time",
            field=models.CharField(
                choices=[
                    ("under_5", "Less than 5 minutes"),
                    ("5_to_10", "5–10 minutes"),
                    ("10_to_15", "10–15 minutes"),
                    ("15_to_20", "15–20 minutes"),
                    ("over_20", "More than 20 minutes"),
                ],
                default=3,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="questionnaire_ease",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very difficult"),
                    (2, "2 = Difficult"),
                    (3, "3 = Neutral"),
                    (4, "4 = Easy"),
                    (5, "5 = Very easy"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="registration_ease",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very difficult"),
                    (2, "2 = Difficult"),
                    (3, "3 = Neutral"),
                    (4, "4 = Easy"),
                    (5, "5 = Very easy"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="risk_factor_explanation_usefulness",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Not useful"),
                    (2, "2 = Slightly useful"),
                    (3, "3 = Neutral"),
                    (4, "4 = Useful"),
                    (5, "5 = Very useful"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="risk_level_clarity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very unclear"),
                    (2, "2 = Unclear"),
                    (3, "3 = Neutral"),
                    (4, "4 = Clear"),
                    (5, "5 = Very clear"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="risk_report_ease",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very difficult"),
                    (2, "2 = Difficult"),
                    (3, "3 = Neutral"),
                    (4, "4 = Easy"),
                    (5, "5 = Very easy"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="suggested_improvements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientfeedback",
            name="understands_risk_score",
            field=models.CharField(
                choices=[
                    ("no", "No, not at all"),
                    ("somewhat", "Yes, somewhat"),
                    ("well", "Yes, I understand it well"),
                ],
                default=3,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="patientfeedback",
            table="patient_feedback",
        ),
    ]
