# Generated by Django 5.2.3 on 2026-07-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_patientfeedback_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicianfeedback",
            name="rating",
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="additional_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="alignment_with_clinical_judgement",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Strongly disagree"),
                    (2, "2 = Disagree"),
                    (3, "3 = Neutral"),
                    (4, "4 = Agree"),
                    (5, "5 = Strongly agree"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="clear_action_feedback",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Strongly disagree"),
                    (2, "2 = Disagree"),
                    (3, "3 = Neutral"),
                    (4, "4 = Agree"),
                    (5, "5 = Strongly agree"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="clinical_output_relevance",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Not relevant"),
                    (2, "2 = Slightly relevant"),
                    (3, "3 = Neutral"),
                    (4, "4 = Relevant"),
                    (5, "5 = Highly relevant"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="data_entry_intuitiveness",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Not at all intuitive"),
                    (2, "2 = Slightly intuitive"),
                    (3, "3 = Neutral"),
                    (4, "4 = Intuitive"),
                    (5, "5 = Very intuitive"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="feature_importance_usefulness",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Not useful"),
                    (2, "2 = Slightly useful"),
                    (3, "3 = Neutral"),
                    (4, "4 = Useful"),
                    (5, "5 = Very useful"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="instruction_clarity",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very unclear"),
                    (2, "2 = Unclear"),
                    (3, "3 = Neutral"),
                    (4, "4 = Clear"),
                    (5, "5 = Very clear"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="least_useful_feature",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="navigation_ease",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very difficult"),
                    (2, "2 = Difficult"),
                    (3, "3 = Neutral"),
                    (4, "4 = Easy"),
                    (5, "5 = Very easy"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="overall_satisfaction",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very dissatisfied"),
                    (2, "2 = Dissatisfied"),
                    (3, "3 = Neutral"),
                    (4, "4 = Satisfied"),
                    (5, "5 = Very satisfied"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="platform_usage_count",
            field=models.CharField(
                choices=[
                    ("first_time", "This is my first time"),
                    ("2_to_5", "2–5 times"),
                    ("6_to_10", "6–10 times"),
                    ("over_10", "More than 10 times"),
                ],
                default=3,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="prediction_confidence",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = No confidence"),
                    (2, "2 = Little confidence"),
                    (3, "3 = Neutral"),
                    (4, "4 = Moderate confidence"),
                    (5, "5 = High confidence"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="prediction_generation_speed",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very slow"),
                    (2, "2 = Slow"),
                    (3, "3 = Neutral"),
                    (4, "4 = Fast"),
                    (5, "5 = Very fast"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="prediction_understandability",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very confusing"),
                    (2, "2 = Confusing"),
                    (3, "3 = Neutral"),
                    (4, "4 = Understandable"),
                    (5, "5 = Very understandable"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="primary_clinical_role",
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="primary_use_setting",
            field=models.CharField(
                choices=[
                    ("research", "Research"),
                    ("clinical", "Clinical (patient-facing)"),
                    ("both", "Both"),
                    ("not_applicable", "Not applicable"),
                ],
                default=3,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="prior_risk_model_familiarity",
            field=models.CharField(
                choices=[
                    ("regular_user", "Yes, I use them regularly"),
                    ("aware_not_user", "Yes, I am aware of them but do not use them"),
                    ("not_familiar", "No, I was not familiar with them"),
                ],
                default=3,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="requested_features",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="research_recommendation_likelihood",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very unlikely"),
                    (2, "2 = Unlikely"),
                    (3, "3 = Neutral"),
                    (4, "4 = Likely"),
                    (5, "5 = Very likely"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="suggested_interface_improvements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="trust_for_preventative_treatment",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Strongly disagree"),
                    (2, "2 = Disagree"),
                    (3, "3 = Neutral"),
                    (4, "4 = Agree"),
                    (5, "5 = Strongly agree"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="visual_design_rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 = Very poor"),
                    (2, "2 = Poor"),
                    (3, "3 = Neutral"),
                    (4, "4 = Good"),
                    (5, "5 = Excellent"),
                ],
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clinicianfeedback",
            name="years_of_experience",
            field=models.CharField(
                choices=[
                    ("under_2", "Less than 2 years"),
                    ("2_to_5", "2–5 years"),
                    ("6_to_10", "6–10 years"),
                    ("11_to_20", "11–20 years"),
                    ("over_20", "More than 20 years"),
                ],
                default=3,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="clinicianfeedback",
            table="clinician_feedback",
        ),
    ]
