# Generated by Django 5.2.3 on 2026-07-30 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_clinicianpermissions"),
        ("accounts", "0006_remove_clinicianfeedback_rating_and_more"),
    ]

    operations = []
